### PR TITLE
Correct starship initiative formula to include modifiers to piloting

### LINKED ISSUE #706: Incorrect starship initiative formula
image

> A starship’s maximum speed modifies Piloting checks for that starship.
> A ship’s maneuverability also modifies Piloting checks for it.
> The maximum speed of a starship’s thrusters either grants a bonus or imparts a penalty to Piloting checks to fly the vessel, as noted on the table below.

Shouldn't it be
```
1d20 + @pilot.skills.pil.mod + @ship.attributes.pilotingBonus.value + @ship.attributes.systems.engines.mod + @ship.attributes.systems.powerCore.modOther + @additional.modifiers.bonus
```
for the initiative check?

Affected version: 0.19.1

### PR DESCRIPTION
**Pull request by LebombJames**
Closes #706 

Note this does add some `.data.data`s, could refactor to target V10 now if needed

### CODE REVIEW

File: src/module/combat/combat.js [hunk 1]
```diff
@@ -566,8 +570,13 @@ export class CombatSFRPG extends Combat {
...
 
         if (this.getCombatType() === "starship") {
-            parts.push("@pilot.skills.pil.mod");
             rollContext.setMainContext("pilot");
+            if (combatant.actor.data.data.crew.useNPCCrew) {//If an NPC starship, don't apply the static bonus to Piloting from maneuverability/thrusters, as that's included in their piloting bonus
+                parts.push("@pilot.skills.pil.mod", "@combatant.attributes.systems.engines.mod", "@combatant.attributes.systems.powerCore.modOther", "@additional.modifiers.bonus");
+            } else {//Initiative rolls *probably* include system damage
+                parts.push("@pilot.skills.pil.mod", "@combatant.attributes.pilotingBonus.value", "@combatant.attributes.systems.engines.mod", "@combatant.attributes.systems.powerCore.modOther", "@additional.modifiers.bonus")
+            }
+
```
Comment (VelniasQ) [inline src/module/combat/combat.js:579]: I created a separate issue for it. I think they are not related to each other and should be addressed separately.

File: src/module/combat/combat.js [hunk 2]
```diff
@@ -553,9 +553,13 @@ export class CombatSFRPG extends Combat {
 
     _getInitiativeFormula(combatant) {
         if (this.getCombatType() === "starship") {
-            return "1d20 + @pilot.skills.pil.mod"
-        }
-        else {
+            if (combatant.actor.data.data.crew.useNPCCrew) {
+                return "1d20 + @pilot.skills.pil.mod + @combatant.attributes.systems.engines.mod + @combatant.attributes.systems.powerCore.modOther + @additional.modifiers.bonus";
```
Comment (VelniasQ) [inline src/module/combat/combat.js:557]:
```suggestion
                return "1d20 + @pilot.skills.pil.mod + @additional.modifiers.bonus";
```

Comment (VelniasQ) [reply src/module/combat/combat.js:557]: That's because `@combatant.attributes.systems.engines.mod + @combatant.attributes.systems.powerCore.modOther` are already included in `@pilot.skills.pil.mod` of an NPC.

File: src/module/combat/combat.js (hunk 1 above)
Comment (LebombJames) [reply src/module/combat/combat.js:579]: #707 is gonna have to be done separately because of how starship actions are stored and executed. That code there isn't addressing #707, that's #706. (Note that I edited both that function and the one above. That function is the one that has an affect, the one above seems deprecated but I edited it anyway)

File: src/module/combat/combat.js (hunk 2 above)
Comment (LebombJames) [reply src/module/combat/combat.js:557]: This is what I explained to you in the Discord. `@combatant.attributes.systems.engines.mod + @combatant.attributes.systems.powerCore.modOther` are for system damage; if an NPC has a damaged engine or power core, they'll take a penalty to their initiative. This isn't included in the formula as it's dynamic. `@combatant.attributes.pilotingBonus.value` is the bonus from thrusters/maneuverability, which ***is*** included in the NPC's piloting mod so has been omitted from that line there.
